### ISSUE TITLE
How to prepare the Windows enviroment 

### ISSUE THREAD

**Issue by matiasurbano** [alessioalex/ClientManager#2]
I would like to know, how can I prepare the enviroment to run the ClientManager example.

Thanks

**Comment by alessioalex** [comment]
All you have to do is to setup your MongoDB credentials in here: https://github.com/alessioalex/ClientManager/blob/master/config/db.json and then `npm install .` (install all dependencies) and `npm start` (start app in production mode). It works on Windows like it does on OSX / Linux.
