### ISSUE TITLE
Issue running on Windows 7 64 bit

### ISSUE THREAD

**Issue by eranation** [alessioalex/ClientManager#5]
Not sure why, but on windows 7 64bit I get this error, I'm probably missing something... 
but even if I am, I think a more verbal error message would be helpful :) 
(will let you know if I find a solution and will post a pull request if I do)

```
TypeError: Cannot read property 'port' of null
    at ...ClientManager\app.js:61:78
    at utils.loadConfig (...\ClientManager\lib\uti
ls.js:79:13)
    at utils.loadJson (...\ClientManager\lib\utils
.js:26:9)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

**Comment by alessioalex** [comment]
What Node version were you running? I've tested the app with Node 0.6.x on Windows before releasing it and it worked fine.
