### ISSUE TITLE
ClientManager / lib / utils.js has blocking code?

### ISSUE THREAD

**Issue by nicola** [alessioalex/ClientManager#6]
There is a for cycle in checkErr in the file I pointed out in the title, isnt that blocking code?

should you use async.forEach instead?

thanks for clarifying

**Comment by alessioalex** [comment]
It is blocking, however it only performs a superfast check (it doesn't do anything more than evaluating a boolean expression, I'm not doing any heavy processing there). /cc @nicolagreco
